### ISSUE TITLE
Cannot run CLI

### ISSUE THREAD

**Issue by markusmobius** [praeclarum/Iril#5]
I am trying to run the helloworld example as suggested in the docs and keep getting the following error on Windows 11 (clang 14.0.6 - same with clang 15).

```
c:\github\Iril\Cli\bin\Debug\net6.0\publish>iril helloworld.c
iril: info: Parsing 1 files...
iril: info: Compiling...
iril: error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Iril.Compilation.EmitLoadFunction() in /home/runner/work/Iril/Iril/Iril/Compilation.cs:line 1891
   at Iril.Compilation.Compile() in /home/runner/work/Iril/Iril/Iril/Compilation.cs:line 279
   at Cli.Program.Main(String[] args) in /home/runner/work/Iril/Iril/Cli/Program.cs:line 147
```

The helloworld example compiles fine when running
```
clang helloworld.c
```

I am new to LLVM and probably do something obviously wrong - any help is much appreciated.

**Comment by memsom** [comment]
I get the same, even if I compile a very simple program (literally a `printf` in a main function)

```c
#include <stdio.h>     
                       
int main()             
{                      
  printf("hello \n");  
  return 0;            
}                      
```

```
D:\projects\tests\iril
λ iril --version
Krueger Systems IRIL 0.9.17.0

D:\projects\tests\iril
λ clang -S -emit-llvm test.c

D:\projects\tests\iril
λ ls
test.c  test.ll

D:\projects\tests\iril
λ iril test.ll
iril: info: Parsing 1 files...
iril: info: Compiling...
iril: error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Iril.Compilation.EmitLoadFunction() in /home/runner/work/Iril/Iril/Iril/Compilation.cs:line 1891
   at Iril.Compilation.Compile() in /home/runner/work/Iril/Iril/Iril/Compilation.cs:line 279
   at Cli.Program.Main(String[] args) in /home/runner/work/Iril/Iril/Cli/Program.cs:line 147
```

**Comment by memsom** [comment]
Okay - update... in the latest code from the repo, this throws on this line in `EmitLoadFunction`:

```c#
mod.GetType (namespac + ".Globals").Methods.Add (md);
```
If I break that down, I get:

```c#
var type = mod.GetType (namespac + ".Globals");  // this is null
var methods = type.Methods; // crash here as type did not resolve, so `Methods` is null
methods.Add (md);  
```
If I get a chance I will see if I can work out more details, but that is why it is failing under Windows.

**Comment by ShadowMarker789** [comment]
Has there been any movement in this item? 

.Net 9 is out now, by the way. 

I'm interested in this project but I also can't get the hello-world sample to work on my Windows machine.

**Comment by memsom** [comment]
> Has there been any movement in this item? 
> 
> .Net 9 is out now, by the way. 
> 
> I'm interested in this project but I also can't get the hello-world sample to work on my Windows machine. 

I don't know what the plan is, but I personally gave up on this soon after it was publicly available as it didn't work consistently then with the supported framework at the time. LLVM is a moving target and the different versions used will generate different llvm intermediate language. Frank probably needs to update it to whatever the Roslyn 8/9 backend is using now.
